export const GENRE_OPTIONS = [
  { value: "", label: "Semua Genre" },
  { value: "action", label: "Action" },
  { value: "adventure", label: "Adventure" },
  { value: "animation", label: "Animation" },
  { value: "barat", label: "Barat" },
  { value: "comedy", label: "Comedy" },
  { value: "crime", label: "Crime" },
  { value: "documentary", label: "Documentary" },
  { value: "drama", label: "Drama" },
  { value: "family", label: "Family" },
  { value: "fantasy", label: "Fantasy" },
  { value: "history", label: "History" },
  { value: "horror", label: "Horror" },
  { value: "indo", label: "Indo" },
  { value: "jav", label: "JAV" },
  { value: "music", label: "Music" },
  { value: "mystery", label: "Mystery" },
  { value: "romance", label: "Romance" },
  { value: "science-fiction", label: "Science Fiction" },
  { value: "film-semi", label: "Semi" },
  { value: "film-semi-barat", label: "Semi Barat" },
  { value: "semi-jepang", label: "Semi Jepang" },
  { value: "film-semi-jepang", label: "Semi Jepang (Alt)" },
  { value: "semi-korea", label: "Semi Korea" },
  { value: "film-semi-korea", label: "Semi Korea (Alt)" },
  { value: "film-semi-philippines", label: "Semi Philippines" },
  { value: "tak-berkategori", label: "Tak Berkategori" },
  { value: "thriller", label: "Thriller" },
  { value: "tv-movie", label: "TV Movie" },
  { value: "war", label: "War" },
  { value: "western", label: "Western" },
];

export const YEAR_OPTIONS = [
  { value: "", label: "Semua Tahun" },
  ...[2026,2025,2024,2023,2022,2021,2020,2019,2018,2017,2016,2015,2014,2013,
      2012,2011,2010,2009,2008,2007,2006,2005,2004,2003,2002,2001,2000,
      1997,1996,1983,1980,1978,1974,1960]
    .map((y) => ({ value: String(y), label: String(y) })),
];

export const COUNTRY_OPTIONS = [
  { value: "", label: "Semua Negara" },
  { value: "australia", label: "Australia" },
  { value: "bangladesh", label: "Bangladesh" },
  { value: "belgium", label: "Belgium" },
  { value: "brazil", label: "Brazil" },
  { value: "canada", label: "Canada" },
  { value: "china", label: "China" },
  { value: "croatia", label: "Croatia" },
  { value: "denmark", label: "Denmark" },
  { value: "egypt", label: "Egypt" },
  { value: "finland", label: "Finland" },
  { value: "france", label: "France" },
  { value: "germany", label: "Germany" },
  { value: "greece", label: "Greece" },
  { value: "hong-kong", label: "Hong Kong" },
  { value: "hungary", label: "Hungary" },
  { value: "india", label: "India" },
  { value: "indonesia", label: "Indonesia" },
  { value: "iran", label: "Iran" },
  { value: "ireland", label: "Ireland" },
  { value: "israel", label: "Israel" },
  { value: "italy", label: "Italy" },
  { value: "japan", label: "Japan" },
  { value: "korea", label: "Korea" },
  { value: "malaysia", label: "Malaysia" },
  { value: "mexico", label: "Mexico" },
  { value: "netherlands", label: "Netherlands" },
  { value: "new-zealand", label: "New Zealand" },
  { value: "nigeria", label: "Nigeria" },
  { value: "norway", label: "Norway" },
  { value: "pakistan", label: "Pakistan" },
  { value: "philippines", label: "Philippines" },
  { value: "poland", label: "Poland" },
  { value: "portugal", label: "Portugal" },
  { value: "romania", label: "Romania" },
  { value: "russian-federation", label: "Russia" },
  { value: "saudi-arabia", label: "Saudi Arabia" },
  { value: "serbia", label: "Serbia" },
  { value: "singapore", label: "Singapore" },
  { value: "south-africa", label: "South Africa" },
  { value: "spain", label: "Spain" },
  { value: "sweden", label: "Sweden" },
  { value: "switzerland", label: "Switzerland" },
  { value: "taiwan", label: "Taiwan" },
  { value: "thailand", label: "Thailand" },
  { value: "turkey", label: "Turkey" },
  { value: "ukraine", label: "Ukraine" },
  { value: "united-arab-emirates", label: "UAE" },
  { value: "united-kingdom", label: "United Kingdom" },
  { value: "usa", label: "USA" },
  { value: "viet-nam", label: "Vietnam" },
];

export const QUALITY_OPTIONS = [
  { value: "", label: "Semua Kualitas" },
  { value: "hd", label: "HD" },
  { value: "hdcam", label: "HDCAM" },
];

export const ORDERBY_OPTIONS = [
  { value: "", label: "Terbaru" },
  { value: "title", label: "Judul (A-Z)" },
  { value: "rating", label: "Rating Tertinggi" },
  { value: "date", label: "Tanggal Rilis" },
];

export const TYPE_OPTIONS = [
  { value: "", label: "Semua Tipe" },
  { value: "movie", label: "Film" },
  { value: "tv", label: "TV Show" },
];
